
const data = {
	
	 "attendance_links": {
	"year_0": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ES4ZPeI6b5tOqvf8jkNwXQABepmM_1Sy9Tnsasiil-DLKw?e=Ga44kR",
    "year_1": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcxTYGPqxO1Og-3l9-Jo-nQBjLLLiCtsduUCcbZYjC1WRQ?e=CdcfeU",
    "year_2": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcAG8H51vtVNuqFDk1sR9ucB68rufL9FvTbuWGhRbfnXMw?e=whDGof",
    "year_3": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWaa9fUD4B9MptBlA8hcBwIBCDgLXOKV0NvBS32Yt-6ycA?e=GDure3",
    "year_4": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EeQ1ILv4aYNMvhHFM_Is-wwB6ePXHcquHxcXM6bO_nvEvg?e=NUyYPo",
    "year_5": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdBZbirMkOZEuKBBZVedKssBEzM8nssN9Misp10LGGtPbg?e=B3wKUm",
    "year_6A": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWwqCo2lhEVEoTAr3SR6xlEB0A0kbSHnPmUOOKq166dtBA?e=sGNRkK",
    "year_6B": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdfDh4v3dBFHsDL0FEgjViQBb8haRrNUec5J_Gx8Sn6d7Q?e=3HUbe3",
    "year_7": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETBdr437_aBEm9Rk4gM0ITwBu50FV5o-NAkEVr-2sTdGqw?e=E7TqbJ",
    "year_8": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ER9pUjxAhQpCvDjnS-MAlTwBvb4d7zLB_0Bg47n8j40SkQ?e=zxSEV1",
    "year_9": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETRCb88xtEZDuA_S7HRMZDwB-g8fEOO2EdRkCn4wjQDgpA?e=L8VwFl",
    "year_10": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eb65xddQ5aVOqD6m-j1Z_N8BkGpRH0560kgW5BemPIg_tw?e=xs3zZH",
    "year_11": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXaWughW5DhMiVQoMVxXQV0B3RCE1qcRpMRTOYn3kntX8Q?e=2xN7Em",
    "year_12": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EY8FXWuIS7xAn1nr3iARlw8BHl_9H2PTcKbMi_cdfM5R-A?e=xE7xI4",
    "year_13": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXEM4eAyqexKg1Ld6Xo-0YYBE8YQVItMenZ9Xb-Fl-DnNA?e=xMBM4S"
	  },
	  
	  
    "passcodes": {
        "teacher1": {
            "name": "Teacher 1",
            "subjects": ["3_EN", "3_MA", "3_SC"],
            "homeroom": "report_card_year3",
			"workspace": "workspace_teacher1"
        },
        "teacher2": {
            "name": "Teacher 2",
            "subjects": ["4_EN", "4_MA", "4_SC"],
            "homeroom": "report_card_year4",
			"workspace": "workspace_teacher2"
        },
        "teacher3": {
            "name": "Teacher 3",
            "subjects": ["5_EN", "5_MA", "5_SC"],
            "homeroom": "report_card_year5",
			"workspace": "workspace_teacher3"
        },
        "teacher4": {
            "name": "Teacher 4",
            "subjects": ["6A_EN", "6A_MA", "6A_SC"],
            "homeroom": "report_card_year6A"
        },
        "teacher5": {
            "name": "Teacher 5",
            "subjects": ["6B_EN", "6B_MA", "6B_SC"],
            "homeroom": "report_card_year6B"
        },
		
		  "adminOfficer": {
            "name": "Admin Officer",
            "role": "admin_officer"
			  },
			
        "admin": {
            "name": "Admin",
            "subjects": "all",
            "homeroom": "all",  // Admin can access all report cards
			"role": "admin",
			"workspace": "all"
        }
    },


    "links": {
		
		
		"lac": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbZ2mtH7ZVtOjtf4-Pug8gMBY_AXYOx424kwN_YhzHJoTQ?e=buIXip",
        "charguia": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EegsqjrYJz1FksYT-fel6v0BbtIu5BzM_g1hejheC4GHtw?e=svf1Hm",
		"student_lists": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUuugrXLwG5Nmjny5kOuSooBr7gw4jcKx56fTcy47QzIzg?e=c6N2gw",
		 "school_database": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETctFyqP7YJIvJi84sjrFGcBFU7D0yLzCiPLv7mSzrY-eA?e=shN7jW",
		
		"workspace_teacher1": "http://workspace_link_teacher1",
        "workspace_teacher2": "http://workspace_link_teacher2",
		 "workspace_teacher3": "http://workspace_link_teacher3",
		
        "disciplinary_lac": "http://disciplinary_link_lac",
        "disciplinary_charguia": "http://disciplinary_link_charguia",

		
		 "report_card_year3": "http://reportcard_link_year3",
    "report_card_year4": "http://reportcard_link_year4",
    "report_card_year5": "http://reportcard_link_year5",
    "report_card_year6A": "http://reportcard_link_year6A",
    "report_card_year6B": "http://reportcard_link_year6B",
    "report_card_year7": "http://reportcard_link_year7",
    "report_card_year8": "http://reportcard_link_year8",
    "report_card_year9": "http://reportcard_link_year9",
    "report_card_year10": "http://reportcard_link_year10",
    "report_card_year11": "http://reportcard_link_year11",
    "report_card_year12": "http://reportcard_link_year12",
    "report_card_year13": "http://reportcard_link_year13",
        "3_EN": "http://link3EN",
        "3_MA": "http://link3MA",
        "3_SC": "http://link3SC",
        "3_PH": "http://link3PH",
        "3_BI": "http://link3BI",
        "3_CH": "http://link3CH",
        "3_BU": "http://link3BU",
        "3_IC": "http://link3IC",
        "3_GP": "http://link3GP",
        "3_AR": "http://link3AR",
        "3_TU": "http://link3TU",
        "3_FR": "http://link3FR",
        "3_IS": "http://link3IS",
        "3_PE": "http://link3PE",
        "3_ART": "http://link3ART",
        "3_MU": "http://link3MU",
        "4_EN": "http://link4EN",
        "4_MA": "http://link4MA",
        "4_SC": "http://link4SC",
        "4_PH": "http://link4PH",
        "4_BI": "http://link4BI",
        "4_CH": "http://link4CH",
        "4_BU": "http://link4BU",
        "4_IC": "http://link4IC",
        "4_GP": "http://link4GP",
        "4_AR": "http://link4AR",
        "4_TU": "http://link4TU",
        "4_FR": "http://link4FR",
        "4_IS": "http://link4IS",
        "4_PE": "http://link4PE",
        "4_ART": "http://link4ART",
        "4_MU": "http://link4MU",
        "5_EN": "http://link5EN",
        "5_MA": "http://link5MA",
        "5_SC": "http://link5SC",
        "5_PH": "http://link5PH",
        "5_BI": "http://link5BI",
        "5_CH": "http://link5CH",
        "5_BU": "http://link5BU",
        "5_IC": "http://link5IC",
        "5_GP": "http://link5GP",
        "5_AR": "http://link5AR",
        "5_TU": "http://link5TU",
        "5_FR": "http://link5FR",
        "5_IS": "http://link5IS",
        "5_PE": "http://link5PE",
        "5_ART": "http://link5ART",
        "5_MU": "http://link5MU",
        "6A_EN": "http://link6AEN",
        "6A_MA": "http://link6AMA",
        "6A_SC": "http://link6ASC",
        "6A_PH": "http://link6APH",
        "6A_BI": "http://link6ABI",
        "6A_CH": "http://link6ACH",
        "6A_BU": "http://link6ABU",
        "6A_IC": "http://link6AIC",
        "6A_GP": "http://link6AGP",
        "6A_AR": "http://link6AAR",
        "6A_TU": "http://link6ATU",
        "6A_FR": "http://link6AFR",
        "6A_IS": "http://link6AIS",
        "6A_PE": "http://link6APE",
        "6A_ART": "http://link6AART",
        "6A_MU": "http://link6AMU",
        "6B_EN": "http://link6BEN",
        "6B_MA": "http://link6BMA",
        "6B_SC": "http://link6BSC",
        "6B_PH": "http://link6BPH",
        "6B_BI": "http://link6BBI",
        "6B_CH": "http://link6BCH",
        "6B_BU": "http://link6BBU",
        "6B_IC": "http://link6BIC",
        "6B_GP": "http://link6BGP",
        "6B_AR": "http://link6BAR",
        "6B_TU": "http://link6BTU",
        "6B_FR": "http://link6BFR",
        "6B_IS": "http://link6BIS",
        "6B_PE": "http://link6BPE",
        "6B_ART": "http://link6BART",
        "6B_MU": "http://link6BMU",
        "7_EN": "http://link7EN",
        "7_MA": "http://link7MA",
        "7_SC": "http://link7SC",
        "7_PH": "http://link7PH",
        "7_BI": "http://link7BI",
        "7_CH": "http://link7CH",
        "7_BU": "http://link7BU",
        "7_IC": "http://link7IC",
        "7_GP": "http://link7GP",
        "7_AR": "http://link7AR",
        "7_TU": "http://link7TU",
        "7_FR": "http://link7FR",
        "7_IS": "http://link7IS",
        "7_PE": "http://link7PE",
        "7_ART": "http://link7ART",
        "7_MU": "http://link7MU",
        "8_EN": "http://link8EN",
        "8_MA": "http://link8MA",
        "8_SC": "http://link8SC",
        "8_PH": "http://link8PH",
        "8_BI": "http://link8BI",
        "8_CH": "http://link8CH",
        "8_BU": "http://link8BU",
        "8_IC": "http://link8IC",
        "8_GP": "http://link8GP",
        "8_AR": "http://link8AR",
        "8_TU": "http://link8TU",
        "8_FR": "http://link8FR",
        "8_IS": "http://link8IS",
        "8_PE": "http://link8PE",
        "8_ART": "http://link8ART",
        "8_MU": "http://link8MU",
        "9_EN": "http://link9EN",
        "9_MA": "http://link9MA",
        "9_SC": "http://link9SC",
        "9_PH": "http://link9PH",
        "9_BI": "http://link9BI",
        "9_CH": "http://link9CH",
        "9_BU": "http://link9BU",
        "9_IC": "http://link9IC",
        "9_GP": "http://link9GP",
        "9_AR": "http://link9AR",
        "9_TU": "http://link9TU",
        "9_FR": "http://link9FR",
        "9_IS": "http://link9IS",
        "9_PE": "http://link9PE",
        "9_ART": "http://link9ART",
        "9_MU": "http://link9MU",
        "10_EN": "http://link10EN",
        "10_MA": "http://link10MA",
        "10_SC": "http://link10SC",
        "10_PH": "http://link10PH",
        "10_BI": "http://link10BI",
        "10_CH": "http://link10CH",
        "10_BU": "http://link10BU",
        "10_IC": "http://link10IC",
        "10_GP": "http://link10GP",
        "10_AR": "http://link10AR",
        "10_TU": "http://link10TU",
        "10_FR": "http://link10FR",
        "10_IS": "http://link10IS",
        "10_PE": "http://link10PE",
        "10_ART": "http://link10ART",
        "10_MU": "http://link10MU",
        "11_EN": "http://link11EN",
        "11_MA": "http://link11MA",
        "11_SC": "http://link11SC",
        "11_PH": "http://link11PH",
        "11_BI": "http://link11BI",
        "11_CH": "http://link11CH",
        "11_BU": "http://link11BU",
        "11_IC": "http://link11IC",
        "11_GP": "http://link11GP",
        "11_AR": "http://link11AR",
        "11_TU": "http://link11TU",
        "11_FR": "http://link11FR",
        "11_IS": "http://link11IS",
        "11_PE": "http://link11PE",
        "11_ART": "http://link11ART",
        "11_MU": "http://link11MU",
        "12_EN": "http://link12EN",
        "12_MA": "http://link12MA",
        "12_SC": "http://link12SC",
        "12_PH": "http://link12PH",
        "12_BI": "http://link12BI",
        "12_CH": "http://link12CH",
        "12_BU": "http://link12BU",
        "12_IC": "http://link12IC",
        "12_GP": "http://link12GP",
        "12_AR": "http://link12AR",
        "12_TU": "http://link12TU",
        "12_FR": "http://link12FR",
        "12_IS": "http://link12IS",
        "12_PE": "http://link12PE",
        "12_ART": "http://link12ART",
        "12_MU": "http://link12MU",
        "13_EN": "http://link13EN",
        "13_MA": "http://link13MA",
        "13_SC": "http://link13SC",
        "13_PH": "http://link13PH",
        "13_BI": "http://link13BI",
        "13_CH": "http://link13CH",
        "13_BU": "http://link13BU",
        "13_IC": "http://link13IC",
        "13_GP": "http://link13GP",
        "13_AR": "http://link13AR",
        "13_TU": "http://link13TU",
        "13_FR": "http://link13FR",
        "13_IS": "http://link13IS",
        "13_PE": "http://link13PE",
        "13_ART": "http://link13ART",
        "13_MU": "http://link13MU"
		  
    },
	
	 
};
