const data = {

"attendance_links": {
	"lac3_attendance": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYMaVIjCFkhLjal9ILZ1BgYB6jNBnOkDQS0mFYRw55fXQQ?e=oA8Ye4",
	"charguia_attendance": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZQT1myrWpFIt7lGMjjPnPMBrrFiPmON5scHGgkf8UT3Zw?e=p0S4Db"
},

"subjects_links": {
 "y3_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUH6IEQq7MVJnDcw6gLfpOMB07Xw2n4GrPhUJyiTa_sUxA?e=oPAaYD",
    "y3_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdaI-dAJuHhEmmuceH-bXrYBYFu32gs0L7VJ0GYuvm0MVQ?e=OtDrgD",
    "y3_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWLsZYcgl-xMqfFJqI59CjwBDpiaJKI3YjcrSvlGDUnEPA?e=61lp5L",
    "y3_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESvs-RM3q-5OixOKVJBZyw8BFriTelm-ZrIe7crMvQthOA?e=c4EcBM",
    "y3_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZtRiko4Z1dDoqhQXujTq9cBAneg-EPpaZUrTa7YPXLQ3g?e=sc7deJ",
    "y3_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVGMoeWVG59CgZmmSEC9ltIBh-rnlzFvMZBuVg2MMnnQdg?e=mToXZd",
    "y3_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVElFUXrYe5HosFizei4AycBxXY6xIV1Ay5ZNXh7KfPsyQ?e=aMZ0qz",
    "y3_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETpKxn6GzQNCma3NANd5UqcB_xOJJZAQG1bx1VJ3mrUC5Q?e=BYCbCq",
    "y3_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcguNHJQTLNAp8AssKqtyGEBye94o8umgalZ-Yna43nfig?e=i3c1sf",
    "y3_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZprCo8TXahDsOnx6JWCZlQBN7-SevjOiN4FjnvuciC17g?e=gSmyQD",
    "y3_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZbSFyzIK65KmTqc_pyd-i0BoTTwIJmmZk5JtdIkCH54uA?e=2J6Cwi",
    "y3_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfcNDIVYAsBOl58iD2KP4XsB373KKog25VJ5Gj-xGMiA2Q?e=b4hjYS",
    "y3_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERfWYtbA2cRJrwhmb2cXPYkBTGq5mc8mCz0RJFB3UneoeQ?e=fuhd7W",
    "y3_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfQPdiME2CdHuFEUdib4U78BaiSCxdetHFk_cgs0s0Vbkg?e=BKstc0",
    "y3_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXPtOQjcCXdHgGyN_fo5mMIBrsgMnfw7oHv_dBc_goGC7Q?e=GPW9aB",
    "y3_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ebwn9c7TuLxNji0ja9Fw6VYBhetxPDarrEbOqA1hj6pA9Q?e=gqbISw",
    "y3_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfoaDiEiCLVNuXsrdtr6QCIBArNnYJ4cEyvy4hjZm_4YzA?e=JMF0QE",
    "y3_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaQtWjKwwAVJqnzfxENkhE0BqVWmHvkIkwsWXompd2bL5A?e=N2ykiB",
    "y3_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVNEIfn6rltIg3wsjdJyg6IBMeKBFpy9PvpGfkzApbN3Rg?e=mRNrKj",
    "y3_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUEFYX-iaANCm8u2LUFPZYEBaqx8KSZfsgUfggQJQkrDSA?e=f1jou3",
    "y3_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZtYP5gZKZ5BhTRw1PtDVZsBTYNigYmfGUMZ-8QuQmbdow?e=lL7OcE",
    "y4_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUaKhBTQkUFJvC2DyH8IX9wBiQkCU9i0UoG9F0lZlOj5tQ?e=d5Lyn9",
    "y4_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdaiGDX_jBJIniPzCk6wYc0BYg6qe-fXwp7U3yIRpPqxrg?e=z3HfV6",
    "y4_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfuEJdG8zDtCmPcai1-AYf0Bw1JJpD8RuHmnpHYOlRU4rg?e=t0PCs1",
    "y4_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EedPCa6it29Kt7Y1WvAkYqEBMlFgO1Kc5Zie75QSfk5nXQ?e=HoV6oe",
    "y4_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERX6eqLFbrJFom2SShwUf-0B6WHUTv9PCM0ia-fhwxyMhQ?e=WMNHAI",
    "y4_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EY6LPVpiTulLlkJe_W7sJvcB9LfCk24WJeid6mb4Rxo7Rw?e=HcojtX",
    "y4_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbtWNjOdSWVAkHL2dKyhm7MBdqYK9oMoJ83javidujs5lA?e=4nnYdK",
    "y4_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERQVsjqDGrZMiS7nC5EyZyABaQih4EJ_nLjnD0gXiSb2ag?e=ul9Gao",
    "y4_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZS2yGBCrqJOqRwquS1BoNUBGkSh0qd3hMS5dbmH7uGi7w?e=WdDSkQ",
    "y4_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXiaQ9l4tShPsoHlNIQxzG0BjWFdPt2aJf9_egrxiZASOQ?e=gUnFzx",
    "y4_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcOux9GGLkRFrX78LmjkPxEBPa2HT-nCwcToZBCCeac1nQ?e=z0qbkL",
    "y4_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZSL2V4Rr8dLiERlQxDzF0oBNu_awN_M5LmHCWulNFsDIg?e=O7XZOT",
    "y4_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaB8pU8rtrVIoO8foesERhsBJh6pC5bfaeZiyRP4iKJ0hg?e=tC0PhE",
    "y4_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWQbPSiO_itLtUyNFozbDM4BrAZhFTY75YNAVIb-roeQew?e=GySoRr",
    "y4_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ES2o4d3lodJGktqh4a5JNBwBdo-D1wbhPY3rCWurWgNNgg?e=8ppvfQ",
    "y4_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EROyi2Nov8pJiVJIYEnF5zYBLdXAb2f_ZjUMY0fOmhRbrw?e=tXxQru",
    "y4_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ES22q5Zw_y1AgSf8ZtXavlMBCJ0DNwPgZyBK-XmHfJnOVQ?e=eavXwS",
    "y4_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eb8pJatfMWxBmv1-AwCEWb0B1CjxnRbUCLASo6ibskO7bw?e=dWsfDj",
    "y4_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EeZp6e8UEEJDopGJyXtl34oBbgzCLkjgex5J4oIjhUWMJQ?e=PNGYi3",
    "y4_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EeIZ862dCzFFiKnKU_4zXwQBVge-oN6GjJqkNL1segsqKw?e=wD9cr7",
    "y4_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfjZJXNLvYhDlpHMbqYgDC8BlznW3oPmSMYLUQv8P7J78Q?e=ppIBKl",
    "y5_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQndTpOuW0hMmTpJ5pWESUoB4OS4cE_ChUBVZ-CU59Vq_A?e=RLW5WW",
    "y5_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVMByYO78CFFi7ZpAu7J1UoBSaTMaE4RSMWLkmFpVbHWLw?e=EdY8bi",
    "y5_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQDLyV5uIVFJkouqOd5Xdp4BmN_04hPid_aYuUUrv88idw?e=LKJ7Tc",
    "y5_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVHCY9czjfBKn3spt4CBlagBrFp_iolzygQoOEVRIlkheQ?e=ccOptd",
    "y5_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZ8Eni-9mUZLuJyZv1PwE9cB-jH3ynKZNWnPwYxVAnQxfA?e=Nr9jjf",
    "y5_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EeCI-i0tvfBNqKceONlmmc8BDlWnWyj8eMKMKYyRIMqByw?e=CKYH0C",
    "y5_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQKy6dG3af9LhNhBCVDWFN4BHiH7EQLpJDApNVrQlT4zOQ?e=9cv4ra",
    "y5_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESQ_tNYmumRNt6LQ7otx770Bk-U1KeWiZobL_MIs9DGlCg?e=qnN75k",
    "y5_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXyynEwYrnZGqz2NqyNviy0BpdpuiN2Oob68k_ANb-v25w?e=Tvke12",
    "y5_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVOC_pb8Oi5Psy7B0i73GHgBA77qzbn1LrdKYUcjxKrmxQ?e=mamHqy",
    "y5_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESBXfmvctw9Gv_b4MLwYJ8IBoJwx0oX4NZNELM0P369Hew?e=nTXqKm",
    "y5_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYoR5LKR8j1IoIpQAeNMsqABde6xQHyaAPRUY6oy2sshKg?e=Pvj9r6",
    "y5_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaxoJF3w2LdAlX_DkVRM8IIB36tfR1q-EaAHxYTyN2NRBg?e=KXaoWb",
    "y5_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfvFN6hEqypLhkrJmysnh4YBq7PMv9Gzt9fqCzmpuaEENg?e=36pR01",
    "y5_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbzJvU_5PwhJlMG_NpGCKgkB17-rTyidFh1-7JdgGszrow?e=1uqFhp",
    "y5_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWIt7K86bxlPofp49VgIzp8BOqvKHQP7ZL3UjkQVD8G9Hw?e=bgjAkq",
    "y5_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWydnbfLU2VCsD5njtHAMNYB32JBB5S6sPhpCnDUxTJyCQ?e=CNFh5J",
    "y5_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETyH6BKBiAhAqwjmBoAUubsBnhEwO-zHB26SXUUpeNSSJA?e=SxFHMk",
    "y5_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXqm4ezowIRJtQPn1e2oC9sBLUDdZj7dF1dRC_k2pN-LbQ?e=Ud8jqi",
    "y5_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERArAtX5iMtGkATRgLkhjfQBqoS1qKZEjEZM68cVTiUkUw?e=uCSNBy",
    "y5_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EShtgkdvMD1IrkAB38kbrzgBMlAyg4482qLpcIezqxQcxQ?e=LZDQUb",
    "y6A_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVSDEIFRDqFNk-sYwfneu2MBva_FxEONozfzO4Ee-6RNeg?e=U6zZWS",
    "y6A_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYWi50rSy8FFqtkhAxnb3RUBibN9ixk4Yjq5l8vO_bMrkQ?e=sM0W9a",
    "y6A_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EacqB4TctUBJiFyDPF1QkYMBAifgZtBEmz9XQQwR3yaJSA?e=5LjgFk",
    "y6A_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWP3DmLR6tRAlhEtUGkjYq4BGMbNJ8W-rB0CD7SVJeP1XQ?e=u0Egyf",
    "y6A_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERSZC8owoRxCnWfuiz-PpBQBs-WD93FBHce9uGKTiX-wsA?e=cPTZdh",
    "y6A_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQZ3p15Nxs5FsDYcBbYjHl0B0tEu6mW4akYO3sU5PLONyA?e=bsbD5b",
    "y6A_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZUsTvnTXMpKqii2EHEElsUB_C0p10k9HSbrxDOhV9hodQ?e=QcBIhc",
    "y6A_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETiHnEvGflZNmF9zjxONbiwBlTa5hrOQNr5Ki1zZpGG3ww?e=0e51au",
    "y6A_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXAoDezdbQhBsHQk6gE8WkkBEptV-a8hx-XQem57nMYnQg?e=ucKg5R",
    "y6A_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfyjKSXdHZFFrgOr8q1RiGkBhb7BTXiVBn9YAGmFX2V5Nw?e=hwvnbk",
    "y6A_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZCL31xcWxxKnFXY7MxEW7kBCKy1rSQ94g1dboky8vYcQw?e=lqgWRJ",
    "y6A_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESZ9XD_QVwZKhjjt6RPIImUBrro57i7J7wMIWLZss7y_CA?e=86vTUe",
    "y6A_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EczZzk7eho9Pt7mkSl8j6hcBlXNwaYB2WeBp0Zt-ScvdoA?e=Ih5CKB",
    "y6A_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfnoKCRRGf9Ctj5nETexALAB8czs3KyFAzZc6hayhlrbog?e=ELUPHT",
    "y6A_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQhGdR6Gt8BPkEfuwzz8aoUBZRmc9ceXO-6AEB9hQwdC3A?e=9V3xTC",
    "y6A_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETz_5ZFyOxxHlPJtkSm21C8BmWn1JukO-2TVvPBljqKzxQ?e=bVdPQV",
    "y6A_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcQ6K5ZkWXFHphuLdJHMs_EBMsprJSawrKJtB3e9wKlKpA?e=EX2Kxy",
    "y6A_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETJvsF60QQdLnRU4oJf827YBfp4yFi56oywjPlUDlEZo4g?e=0RNfND",
    "y6A_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZ9LqYm3U4RIiXPrdR_4HFQBVKeFKkM_8nksnx2-zJFHVg?e=0UCNZb",
    "y6A_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZVyWwgs2_tJjvOWxv8mqTIBYgiqu02DLnLZaHcqQy0rRw?e=Qu890J",
    "y6A_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ebk6o75SqgxBiInsB0eyuqYBlnFe4G_B2OSq9ZFapxqkZg?e=8v6Gxg",
    "y6B_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EefU21kmHbVLsxS2-xeEYGwBz8-vZJuKvDjQ6YQcj6FvPA?e=tOZb6J",
    "y6B_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERGz-5sXLYpHqyiy7EVr_pUBaLmDgNcmkx7MExPIz-FR_Q?e=P7EtBE",
    "y6B_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Efuy9-gbLNtDtLUd3xHMEmEB3VoT3B_eRmrXbC5nIHgbtA?e=mCHStG",
    "y6B_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZOb_mQE8hRHvSM4b0f6beIB9M8vy5EoBDFWA4qxfXHgjA?e=gVcYLW",
    "y6B_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdeKTst-EBNGmt4kXPUYqz0BlTvbSyETsvP0Rzba5tpVCg?e=QCNHda",
    "y6B_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZs5vTMgoLJKmHajiqswjycB0EBR15ClVWZgn8uz2R350Q?e=KB4w78",
    "y6B_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZrD8KDXTRBDoSFCV8QDddQBaerXKiXR2bxbpsqSvzsWCg?e=vuyVeW",
    "y6B_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYSKWQWrlwZKjSv-5XBnYX0BGAYOIVJw8nPk8A4ZE0EAIw?e=a2Ohvv",
    "y6B_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERqm3OnwrAdLiArRX9MQGQQBHV_-grjEcgvjYxIsNh70iA?e=bnwcFm",
    "y6B_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERp_xLcNdlJBtxtNctOnnmQBnTQoo2egTYzXZhK_xrzxeQ?e=kidpPT",
    "y6B_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EW8S-sHdG65Dig6TvPHEARIBKfFep78J1yQSHv69bLdsFw?e=EAsh6L",
    "y6B_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWWZ3nc7zDpErLYhDiU6t5IBTu0j0T8sLBf9AQ6Tlye86A?e=FgpY1K",
    "y6B_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcQ_bGpkdiFPh9cdQjR7WhgB5jFDwGLy8FXCJJC5fQwNcg?e=wH8WJ8",
    "y6B_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eby8eymMgrlChBeOfpTDHn0BwmZ0Qi1YEBR8kPiyf4EWmg?e=o1SH7A",
    "y6B_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVO81VT_WnlIpYfpLecD9o0BDCT5WIGbZYfbQHTHKG_sIA?e=2SGlSu",
    "y6B_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdEqkZrFnUFLnaTCQXXS6OIBYt5uL9g6YFcpZ4zU0Q3qVg?e=p0VWc2",
    "y6B_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXgCKRwnmp1GhexpD9_l0YIBxlIEroe0SSyWQqurkoH20A?e=CDo3E1",
    "y6B_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWuE7RDyteJOutnOxph_eVcBVanM26icsqDwNNIE5Myuzw?e=vCqkId",
    "y6B_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EeYPY7px2TFJrYSkgTMxANgBYN3H0y4A21CUGAnbbliKSg?e=lx6huE",
    "y6B_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ea9WwEJuyo1Ag4c3SxpaVywBZvHxFO_m0pXIIwKvOkGI5Q?e=qWjjbr",
    "y7_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcGS5N98teVPsmJMPR5wi04Be1aKdWstpdxGlA0KQEwmzg?e=IzSkrq",
    "y7_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EV9EED409KVLjxr8HyT1w-IBEK1f3C2Kz_V3hZPhvguMQw?e=pTon6P",
    "y7_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUa4TSt2H5BInVWgEkzP7YYBWxLG3luYG3t_KWLX9lUXhw?e=iZhBtR",
    "y7_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ed8kUjHDFEBCnSzs7atWRxEBipcUBX4g1uowKQhUYE3Oyg?e=SQ0mFy",
    "y7_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETNUfQqDty5El3WOrHeJqw4BN1PwgWf_VS48x_8WnKA6pA?e=R0VeFB",
    "y7_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ef0sc5gVGVhKkkS8HfJ8LtsBOvDgmluhmM272FrsNDhbqw?e=Coik5D",
    "y7_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ef_td560eWFPsliKGw-WyqEBS_uuZqYKisNMONbzq2s9nw?e=yRpZSV",
    "y7_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbcDtkTtiEJPpwuDKCN5r1wBqODSmnzj22hAi2IkOXw8vQ?e=7N6eD9",
    "y7_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EY7bn5c8tv5Djz0lRbmthR0BMl9tjCYxs4HGqw4bOBMYyw?e=FIWEfh",
    "y7_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETiiX6T7vdpAnUt-vvCSE74B_sPpUHw4NZo77DIxWecXmA?e=L4EPcI",
    "y7_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EX3o7dPBcjRPk2pklXssIo4Bp7FE3ATkG10gF3TukREoCQ?e=7RiBTJ",
    "y7_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVM4c0F_Om5CjaHQ7SzXXi0BllkduFEvXALjkpVqr_hQiQ?e=vD2fDU",
    "y7_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQpvkWr9I0lGqCvBxURXRbABZq-M0yqL6p8jecoTDc7j4g?e=4TnRnR",
    "y7_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EawF9vaM_QtEsjsWmqcaGH4BoiMxiFRb84Z9cdwb35F18g?e=go6Oyr",
    "y7_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWgBt1LelBVJhV8kXwZyOUIBsy64qOIhfDEE973sbqJpRw?e=8w5XuF",
    "y7_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcO06_Kg7C9LlVnTkOZYAQQBDqWCt9qg6lbbJGvue9qi1A?e=tNMI3r",
    "y7_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQM72NjFHxVAkgTuUSalUQ4BZyxllmjvzwosY0Megeq8UQ?e=FkfHOe",
    "y7_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZLT4PhzFXJNpJqtOtoqfJQBlRXRMmE1M06hmeKQQakzsg?e=iIdklO",
    "y7_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWf7eyCMSb5Fh61vAAxBMxkBrD0WpXBioXAhmZX22GJ4bA?e=46kQb2",
    "y7_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQ1-1Nc2JZBNtridIMB8XcMBihulXmpukGBQ3SnUg9Ih7Q?e=iaw4kV",
    "y7_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ediy4oGyO0BKqvRWYNFcUZ4BX4ZhoPW3kZMjy9hQK4gIQw?e=MYEsxu",
    "y8_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZ8Xmr_5uglCtSq_XoFrR28BvMXNLqIP2MRVGIHKyG86oQ?e=zgwdnA",
    "y8_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EW_C6b0jSyBEutT_Mx_Kw7gBUGoyTyxGybX-jsEZLRQRwg?e=BFUTyz",
    "y8_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERrK-QPdl91Mnf6oVFipuRABVmkr25AY5OrlG8fRE--afQ?e=Q48Smi",
    "y8_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EeCja1ZKUw1Egts-en3dCrQBB213IDvDGCdXJrkqY7EKLg?e=xdIIKi",
    "y8_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETx26ZzbK8xHnS3MqpqtWGYBCwXxs9h_HEX0RwgmcNTkMg?e=ybHsAl",
    "y8_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaqfbOruOQlFp4TyoPeg5-4BGIrbqFUZkPe5N6E06kC6tQ?e=Q6Tqyo",
    "y8_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZYIVv_ZvKZPlHR71pUdkeEBRsKL2KAkD3r85uDlQVY1Ag?e=QX8N7z",
    "y8_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EX_kfgyNuoZFkNyp6bN3YuQB7GXSCfMSeKOt8B3MJ-snsQ?e=9ZFsgs",
    "y8_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQZp9wvt4StFkwTlTyQDcP8BiMJFjTV80lIy1g2bwgEVJA?e=xkjTKj",
    "y8_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EamzXDLLV6BMllEhT2RW8uoBGMAZmr84nIh2Fj56DPhBkw?e=cwjbCX",
    "y8_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eeh5Lg9I5XVAisEeQon__lIBybTOO36ExwvQqwlmls9-nA?e=tajKzc",
    "y8_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbP2ftu1rctGvScu77tEwsEBH91qZFHZ_zgfy4zabNT-RQ?e=dKr8Ii",
    "y8_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERlWW9WpcIJGpfNzPa42BbcBCyEYlPSxSRIy0sHlnT5ZXQ?e=DXf74L",
    "y8_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYxF41AB3r9Aigu-A9ZgnSgByuI_W8yAxOybEJ1sQIHyAQ?e=GNYb1i",
    "y8_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbHSQ3Nk30dBv7eTalDhDlYB6i2Y62pucLs7VYFFFEDxcw?e=0oeZso",
    "y8_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYIypulwjuNIpPluICL3McEBLjxRcpWdACigUsnbovhhuw?e=CadGUU",
    "y8_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaTPjnmFzKlAj6EZx30aAycBBfSj8voMs5Pko029hLiJYg?e=LQ63GO",
    "y8_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EW-9tnYXsxZIsaTKaPlnlBIB7n8AWwd-9yBFREYCG-CTjg?e=uxByuX",
    "y8_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERfkwHjOD1dFhefC-OuCT_MBuZP2jMNbe2r8xDe5qWh7fQ?e=BAPNsA",
    "y8_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbOcgo83oRRIhlbAxO3pPOoB5rQxkqFZL7-FPEspmmOLUA?e=MZn0ZY",
    "y8_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUTjpZyJMf1HqsK0mNsRW6MBP4oVjO8PVkJWgSh5X0tG-g?e=EimDBl",
    "y9_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWerxpxvBxNBjwD1RIqICnYBF3J26qhRo0DJAqRDaMvh7Q?e=Tj51xm",
    "y9_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUApF0OsrOBLorYZhcwSTvEBwnyHzgXieiLU-aJQwGCfhA?e=jv3drg",
    "y9_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZSUJExfV6xBjULDAI7ynAcB3QIHx7xMZjKknxbB0cpl-w?e=f5YEdX",
    "y9_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYo8F1RkacNBt-s4K263LRIBU95cN0CiDU4Idx4_sgKBAQ?e=t29wVO",
    "y9_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EddowLdSoV1Et4kIFaKhZL4BY99q0OX4S8xjybgBODuu3g?e=XaUCmM",
    "y9_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbXa8LnwJQpHhPHu0kLRCEwBCuOic74HwE3h2mHsxAiszg?e=lBmYuL",
    "y9_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETKiVMTRsOJEhsO7LR9-ugMBzmvdB_JUYX80moxQhCAPHw?e=VZ4qM6",
    "y9_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfXE0BTrXXlJsrgjHLaC8wgBQg2O3KHXJCyY3I0AoNBiYQ?e=eccjTN",
    "y9_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUym2CyYjkVFqKol9IjiVrcBF1QTWts2HMhxHsx8n10euw?e=Ls5afW",
    "y9_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdRjlv_mseBOhKSLCpQ9Z7kBlOI3KPqDo_MMCt_mOMKl1w?e=MvJhFH",
    "y9_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESip7QENPiRDiVnEHgHhN0oBdQmuUAfrX_i8BT0VeXGOxg?e=dGNumw",
    "y9_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ET5UkOW3-jlHiBPTeJW_DU0BsjrzhdRT5AP8450vgCyUEw?e=yKb8E1",
    "y9_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcyN9k9ytTZNtqEZ0odzot8BlKgv8KrARo0X_sXMONkvOg?e=qdAaH4",
    "y9_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ee4_9VBdUp9CqT6zhyvcsqEBz_8kA4yp1nCgdW6Xb8je2A?e=W8r5l0",
    "y9_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ea-NiL04skBBtN9zAghHaSoBJPrKk8D-Yybun1p-9uhw6Q?e=ELOzS2",
    "y9_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EX1ZFLi08sVEjxJd2jLrtzMBx7WPXjPg9yOtNOuFNjcF-w?e=3I5JcO",
    "y9_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWKYyC0PKPdGrzIxNdjokQkBTT1MCeLIhKZZ3ARvbb1L_w?e=CykZHe",
    "y9_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ec1Ku9aprQdGobvmUTb4X2oB7s9qht6ni5m7INWEvLVNKw?e=EE3b0l",
    "y9_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYTS3r7ODn9Gj9YWM1U0fl4BXBL38-hb2RlsN53HeINKmw?e=HjB4xs",
    "y9_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXgsOeJTAbhGtP1tbrEqrl4BXio22UdCXwwuUU7QlbVC5g?e=FHlRpT",
    "y9_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaBKvh3G3QpImAe5KVVt464ByEKRfbCUpO3kFjWUI-FlWg?e=EOCAlc",
    "y10_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EReI3ENLvxVKna-J3HBxUgoBkpAU1JjBZNgvPGL2LzYQrw?e=KNijfb",
    "y10_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EW3MAGLcOBNNrKuyDveRpL0BQ_7D-tkt24_q95mKg7Weew?e=2hXa7T",
    "y10_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EX-Kd_Uw9SBBnVI5KNV7R3ABbQJUENO93bblbR4SOkHgWw?e=yxxHu8",
    "y10_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQEqfFLW_tpAnPsnb4vl_QIBnzJLbaf34vbgy2brQ_eiQg?e=eyYliq",
    "y10_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaBjF4sQDsVAuT4sh4vgPnwBCXW3I8AH0Ix_BR_3XDoS8g?e=OLlMRV",
    "y10_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ET5e2xXcmLVHpH2yPK8WtLIB9e9mMezS8LtOgTInm-M3fw?e=05yyJl",
    "y10_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXNdXMCHk21OvM6O1TXJ9dsBKe62qo-EV19kUSLv2I_HJQ?e=Qyb5nB",
    "y10_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eb7FAnZZ43xLl56aJuvTIesBGHE3PB82jDJ-Py_fi7uNPA?e=HSvUZS",
    "y10_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERLbGT9gMNBAn4szFRI6QIAB1Rmm2_SvC7kKm5tWvbgx7Q?e=e2izdE",
    "y10_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXb2Zzh26HpAgIrtsmmBVQ8B74dIWn8k0KTmqk1LgQtpbg?e=pqB1yH",
    "y10_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EX3w7AIY4NVEkkbbbILYiREBXYtginD44olOJYpRyCuOLg?e=5f9DVW",
    "y10_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ee2Mpx6C__FNr7YUIISyM68BUAWFOm89s79CR7ivYV38_g?e=c1AlSF",
    "y10_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESvJbvSd7rNMkPtFqZla6BsBgdDwLiAj1-u1MAL-6qoFjA?e=31K6VJ",
    "y10_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ES1AH9FDZdBMpvKGlTJk9dQBF98UqO8CkXklgiF_OgtIlA?e=6pwGC4",
    "y10_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERT7EduJDuFNlKl2UXlD2PkB6m_wLrF8X4ckAGwI18Sa7g?e=RO4C3v",
    "y10_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERSt1LRmRKlHsUunLre2Em8B5cq2L0dzKu43lYbg0hk9mw?e=DR0VfQ",
    "y10_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESwl5Scuxm9Cg6w6GzuCohABfHl2QGyHMRmLbP-JXVQjgA?e=2hKYZa",
    "y10_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETzhIuB_-gZNgY7uWT8Poi8BrAQJNm1n6iKw2XXhwaNlaw?e=VtpIBE",
    "y10_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVgkO4dqq-NCsm-iaofbLuMBHLU2JuSRfINnrKlgg3l6-A?e=0nk6op",
    "y10_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYIoR6UgVv1NuFg3x9CKjrIBGr_zCIA4i79OVjWBeVaOKQ?e=yf8F7s",
    "y10_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EeyozV2dU5FEtY159UAxYa0Bz-EmK7vcsJnGB-C55qc16g?e=dwJcwm",
    "y11_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVFPZdnvTvFPtLajPrLqICoBepCUPWg0B5rgbVXcoXd5LA?e=2mdBp5",
    "y11_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERVmNlL4fepJqVfkDpBgv9cBb5YUuMK2B5Wf_zGAVcMpFA?e=EyHdOx",
    "y11_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ES7ZLgdlqAlIocUYkoUd5HUBMcMDyTHWdFo9aDUU3Y5dbw?e=NAKJkd",
    "y11_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EU9bOfA8wB5OgJWrtemzaicBVmnFPllCp1g8cIQua6EQOg?e=wgb6mq",
    "y11_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ed0p8vWBxYlImBMYRRI7XFIBtHOp90Qnwo0zywJwNLsrJg?e=aWRCKt",
    "y11_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ef-JeZ6wa89IpbvRRtH6yiEBsSpgaOGeksJ6eWQDuybngA?e=9gz8Pz",
    "y11_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eb67w7jpVlxKrGF3GQTK0WwBVvX44SblEXPsBAmiNzH1cQ?e=5uunsz",
    "y11_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVdRS3nz1ZlLtS4EHUwFykABRplaXnUpHDnfCt5KY4IDog?e=4Gi69u",
    "y11_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EetnuY52QX5Pn9x9K5eHSA4BovDaAEslhDrnQSTE8p-ytw?e=6JH6nc",
    "y11_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eeyb-K8Vy3hGshoG48waqFABYJ4xHyOtWOy9wofTHhsrqg?e=pDh1S9",
    "y11_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZMGrROyyQlIvkouK3H5eO4BFdW-IOzqITqXMvsgzEuDEw?e=HNYxEL",
    "y11_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcfkzThQOlxIsY3AW2bwKvcBpCCmsQgirOGbzCkX7SIR5Q?e=KfSwJd",
    "y11_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eb6UHx5WFgNFre4hdCXorU4BFXWzaTsAh7ybXTysxN2fvw?e=6pNR6U",
    "y11_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQqMhPXs5rpEgXgEZ6U5mJcBJgAuxY7CWhUxD2YvkH70iA?e=ekFhdf",
    "y11_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETzz5TyNGlBAjVFqDOwvFfgBUl-_p3Eu38fHJIS3o9qrlg?e=7BJCI1",
    "y11_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdPibZeKDT9MkgnHwAaw2O0BOSt7n84pYGDnpc0-sp5PbA?e=j5fyoT",
    "y11_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVrcrLYbaiJOhBSZgRHWYf0B38FzxbQoxsCmc4PgJT_1LA?e=k6GAB4",
    "y11_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERKrtZqHfulAm58EeQQ6ThEB53lUDRnAeKh-iqHsPDyvag?e=H2Ode3",
    "y11_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eext4IxqMXpIteMqgXmT7SMBfi-lye18qL1e1Paqv_uVYQ?e=79uRuI",
    "y11_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EVYTc6w4HRxKtqGVtU75_20BFtTmab--HXe4suTxkwHGNw?e=qJHB9s",
    "y11_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbnWzxA63eFKhuxTAVt4M6IBryy2Ns7APrTeja3hNiJ6hg?e=OLZh1p",
    "y12_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ed79LTBxKcZCr9AvCt_EYWIBL6unygz7Poib-uwIqHPyRw?e=bNp3E8",
    "y12_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ecl89zVz3X1Mh4IRYlTOF0cB4nQoo_KzVMUPOnJePi5W8A?e=LU9LoC",
    "y12_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ecdbh7VG0ttPst0cVCV-_9sBA4MtCQ0mS-chjnJXx16saw?e=jpP0J3",
    "y12_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EY_ZK1NVR4hHg0375DiKMXcBQsXt1ppJ1WWawET_tPHueA?e=nUhoah",
    "y12_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESgp4Z3pR7lIuAlCpCqLK2UBeQtUhSAKOAIPyzsq-v_saQ?e=Z3gWeR",
    "y12_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETEbeLKUrPJCmp9bJHDNzRsB2uwacKynknoGabTJzFchwQ?e=7lhPYp",
    "y12_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETEbeLKUrPJCmp9bJHDNzRsB2uwacKynknoGabTJzFchwQ?e=J0Z3Pv",
    "y12_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdtbkvWj69pMhVWcWyJ4-aIBrOL6ke5b8heFqD-IgY5DRg?e=hEG9CE",
    "y12_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZ5GDMuvny9Am9Vf_H0XxWoBoghc8v5mI42hjTv7RL-qGw?e=IyAXNx",
    "y12_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbF3n5IzyeRCjQsyTOK0LasBKmnrT5WQ31TM0b3pc17Cdw?e=yztYsq",
    "y12_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbNhVknweG5BlnNH6I0TI6sBe-WxSI6aylJGAB2PZOmipQ?e=J8Yubx",
    "y12_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXTmwKoGiUpLt2m6n0eUooABpyWYHt444_X2pJMD52-zxg?e=ffozfo",
    "y12_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQ_WDBHXRnZKlRLy0McYkW4BIGMvQ87zij2Xb8LqF0TH9w?e=ChZca3",
    "y12_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ee5MMEixcvBLlrW9oXFXGl8B7N8NTouDqcQtvVA8CMJeYA?e=HuemjW",
    "y12_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EY4wFhe0uKROm8na1-uElZIB6D4Cog3Ai-Vsuy7FPitCSw?e=uP5GHi",
    "y12_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESKzAnS6KPJFhPleWuW7wqABxSo7G86F38TjQ8lyF8JoZA?e=po0Ha2",
    "y12_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERbWQTqhPO9FhgDgi7Gl65oBn4_g5aya7YGcqZmopYm0hA?e=GFJ87B",
    "y12_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESnoSZuTUT1Fiz5z1RYLjPgBtqAb3CDt4n7vgCKHewBbxA?e=6Zz0s8",
    "y12_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EdhlACMd-v5IlyfeKUkSYdYBz56c8X7FMW0rfllJwAZClg?e=15VZZ2",
    "y12_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfABm5Cebc5HkE4E-CD_uBcBQdnVYuF1BY580nfYPirR-Q?e=CoR3p4",
    "y12_wr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfABm5Cebc5HkE4E-CD_uBcBQdnVYuF1BY580nfYPirR-Q?e=3Eh9UB",
     "y13_ar": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQcAN6zMemRJs1yKE9NGW_kBR_kHZ5oYLkqiD8B4N6Pp_g?e=WfWfEu",
    "y13_art": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERYOPOEdwsNKvfRuKuylBMQB6klz1Nu8UYxv1j8tKQo1Ug?e=Ykt5qe",
    "y13_bi": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESBzV-R96d1Ln8WZ6S3AWeQB0oSbKahBeQ5_6PV4x2n-Yg?e=CuBOc5",
    "y13_bu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZ6Tvm0IWVRCmuQOb2ZVLFABkzH5TWWNVZQHJ9gTy0AR5g?e=qtCjyY",
    "y13_ch": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWYFHBVY8MBJncvM3w_rIfEBc_PcY36psjQ1-yaVuP5IgQ?e=dQMCOW",
    "y13_co": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcmskRKovKJLvf3gy7LVv5QB8Vi_ShQGNUl4JmJ-UhdirA?e=AhIKcj",
    "y13_cs": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ET2LbLOxDdNGlDb_ScwFyrkBTipPHd_Z05uHxNkxPZznWw?e=CJLXWx",
    "y13_en": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZCD0o5O1WxIvG5VWwr5JegBY_b8GrqeL2-eGIKWf0asgA?e=iG18TD",
    "y13_fr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWlpFRNEbSZMrX6Z8V81E88BGa-8UDnobeJ9upQ1G2Q9Wg?e=z87yAN",
    "y13_gp": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaiQKcxTAGpGlxgntCQxhKoBQJY_J88fbQOOORZiXi37qA?e=4m3kFJ",
    "y13_his": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbX_6K0wrBJEgckFhxXN9P4Bf7nLZJS-I2mVk3__G54Cvg?e=EcIboF",
    "y13_ic": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EWxqmbzEIFFLu089NSjV91wB6hHm5VY_hY5lNCYulrLhug?e=gLb5kS",
    "y13_is": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EZIpbAHupchNkniq3PhaklYBNSgT4Neq_LYOCpp0SAWhug?e=XkeB7S",
    "y13_ma": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYoVNH_F_rJAn_S6_mPSysEBt4-6oXXeizcufTDnUzRIWA?e=RaeQyG",
    "y13_mu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETteA0nq8cBIsXUa4yBvXoMBE-8oasa08wMpx5VGwRFlmQ?e=OOTtKg",
    "y13_pe": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESr7qpuLfa1DjzyrQlSG-ngB60N0oaN4bjnWi7X6a2ZmIw?e=I8P120",
    "y13_ph": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ERkZGcboXZ9IhBXfXIerw0UBjeT7dnlEMlQD7M02T-Q4cA?e=xNgiac",
    "y13_re": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EcYo-nQoYCBKqVI3gV1_iKYBWDw1pIx2FxvIxnEymbi01Q?e=xYDSOE",
    "y13_sc": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaBTKb1stotFhf4bE7ZH9TIBQie5NrrmFVX-CNPOYt5QSA?e=NBcEGU",
    "y13_tu": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ef1vmc5VYxFMufeEgITcfUQB8nfnabCzmf9rl8R9c1557Q?e=mJ5MhL"

},

"reportCards_links": {
       "y3_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EYwbh7kQ-U1Fl-DanQNg-UwBsSrLgmhXgN6ucDlJgrhqXQ?e=ZD2EBn",
    "y4_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQ9r3BoFD_hNg3D2IuttlVMBgZBLLoe2fJftZpV2zjjq-w?e=YAA1hz",
    "y5_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Eez_Q18olCRAk0DGVgyIm4kBHh0TnSVaI7aRe89QG7aSHg?e=wq6caO",
    "y6A_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EXGNz41ycShMqTCbszzApRsBDkWPW-fX6__DFyhexu5Jyg?e=7NHCKB",
    "y6B_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ET-Qlovu4x1DnsYIJnMP54EBweppcVtI85_RcwL-TrSC7g?e=UwfZkH",
    "y7_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/Ee2KkAbQoTVAivludxAXCj0BlmcLvkwlRIYfWW5Np12R1A?e=idcPlf",
    "y8_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EaxZALH4cWNKgqw8iaUfY4QBrQIV3TzAD13nfL7WEPI-TA?e=NdnFZe",
    "y9_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUIxjdNgL35Dg6m0Sz7v8KsBNqw3wL0lfjn7O4v1CXuwWg?e=pjbbNE",
    "y10_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUDPeZe_cNRGnjPJlMEgfKcBl2K2H771sqjNV3xArAVd5g?e=Vg6M7x",
    "y11_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQIHEjsk0_5ImREmbIPZV0ABZm0ItsKxAf8tBUOX-DpxUA?e=wIGJPt",
    "y12_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EfPleKWuXXpDrfNsbOLXEFkBHQY5XOjEmXq-m0mhAHn_Ew?e=zo06pI",
    "y13_hr": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EQ9SP0Xg499KrHoHSSTODl8B9vNuZZo-dsYyvDzRJ6oP7w?e=jGWTZE"


},
"passcodes": {
    "ad24min": {
            "name": "Admin",
            "subjects": "all", // Admin can access all subjects
            "homeroom": "all",  // Admin can access all report cards
            "role": "admin", // Admin role for accessing everything
            "workspace": "all" // Admin can access all workspaces
        },
		
		 "o5566": { 
            "name": "Officer 1", 
            "role": "admin_officer" 
        },
		
		"1890": {
            "name": "Afef Ferchah",
			"subjects": ["y10_is", "y11_is", "y12_is", "y13_is", "y6A_is", "y6B_is", "y7_is", "y8_is", "y9_is" , "y5_is" , "y4_is", "y3_is", "y7_ar", "y8_ar", "y9_ar"],
			"homeroom": null,
            "workspace": "workspace_1890"
        },

			"7890": {
            "name": "Mouna Saad",
            "workspace": "workspace_7890"
        },

	
        "2789": {
            "name": "Ahlem Bennour",
			"subjects": ["y6A_fr","y6B_fr","y7_fr","y8_fr","y9_fr","y3_fr","y4_fr","y5_fr"],
            "workspace": "workspace_2789"
        },
        "3478": {
            "name": "Ahmet Ali Evlice",
			"subjects": ["y10_tu", "y11_tu", "y12_tu", "y13_tu", "y3_tu", "y4_tu", "y5_tu", "y6A_tu", "y6B_tu", "y7_tu", "y8_tu", "y9_tu"],
			"homeroom": null,
            "workspace": "workspace_3478"
        },
        "8123": {
            "name": "amani daoud",
            "workspace": "workspace_8123"
        },
        "1122": {
            "name": "Amina Karoui",
			"subjects": ["y7_en", "y8_en","y9_en","y7_re","y8_re"],
			"homeroom": "y9_hr",
            "workspace": "workspace_1122"
        },
        "2345": {
            "name": "Amir Jaouani",
			"subjects": ["y12_ph"],
			"homeroom": null,
            "workspace": "workspace_2345"
        },
        "5678": {
            "name": "Amri Hammami",
			"subjects": ["y10_pe", "y11_pe", "y12_pe", "y13_pe"],
			"homeroom": null,
            "workspace": "workspace_5678"
        },
        "1243": {
            "name": "Boshra Mannai",
            "workspace": "workspace_1243"
        },
        "1034": {
            "name": "Chams-Eddine Hemdani",
			"subjects": ["y12_cs", "y13_cs"],
			"homeroom": null,
            "workspace": "workspace_1034"
        },
        "1357": {
            "name": "Emna Ouhibi",
			"subjects": ["y4_ar", "y5_ar", "y6A_ar", "y6B_ar", "y7_ar", "y8_ar", "y9_ar"],
			"homeroom": null,
            "workspace": "workspace_1357"
        },
        "7618": {
            "name": "ghada jemaa",
			"subjects": ["y10_en", "y11_en", "y12_en", "y13_en", "y12_gp"],
			"homeroom": null,
            "workspace": "workspace_7618"
        },
        "6345": {
            "name": "Hamdi Hezzi",
			"subjects": ["y10_ar", "y11_ar"],
			"homeroom": null,
            "workspace": "workspace_6345"
        },
        "8517": {
            "name": "Hazem Ben Sedka",
			"subjects": ["y10_mu", "y11_mu", "y12_mu", "y13_mu", "y3_mu", "y4_mu", "y5_mu", "y6A_mu", "y6B_mu", "y7_mu", "y8_mu", "y9_mu"],
			"homeroom": null,
            "workspace": "workspace_8517"
        },
        "7788": {
            "name": "Hiba Larayek",
			"subjects": ["y10_bu", "y11_bu", "y12_bu", "y13_bu"],
			"homeroom": null,
            "workspace": "workspace_7788"
        },
        "4589": {
            "name": "Ibtihel Arfaoui",
			"subjects": ["y3_en", "y3_gp", "y3_ic", "y3_pho", "y3_sc", "y3_wr"],
			"homeroom": "y3_hr",
            "workspace": "workspace_4589"
        },
        "3344": {
            "name": "Karimen Mnakbi",
			"subjects": ["y10_gp", "y11_gp"],
			"homeroom": null,
            "workspace": "workspace_3344"
        },
	       "5279": {
            "name": "Hichem Maroueni",
			"subjects": ["y6A_en", "y6B_en","y7_gp","y8_gp","y9_gp","y6A_his","y6B_his","y7_his","y8_his","y9_his","y6A_gp","y6B_gp"],
			"homeroom": "y7_hr",
            "workspace": "workspace_5279"
        },
	       "8493": {
            "name": "Rahma El Amri",
			"subjects": ["y7_sc", "y8_sc", "y9_sc"],
			"homeroom": null,
            "workspace": "workspace_8493"
        },
        "5690": {
            "name": "Manel Touihri",
			"subjects": ["y10_ch", "y11_ch", "y12_ch", "y13_ch"],
			"homeroom": null,
            "workspace": "workspace_5690"
        },
        "3678": {
            "name": "maryem sellini",
			"subjects": ["y10_fr", "y11_fr", "y3_fr", "y4_fr", "y5_fr", "y6A_fr", "y6B_fr", "y7_fr", "y8_fr", "y9_fr", "y12_fr"],
			"homeroom": null,
            "workspace": "workspace_3678"
        },
        "1245": {
            "name": "Mohamed Alhomsi",
			"subjects": ["y10_ma", "y13_ma"],
			"homeroom": "y13_hr",
            "workspace": "workspace_1245"
        },
        "2367": {
            "name": "Nairouz Ben Hmida",
			"subjects": ["y5_en", "y5_gp", "y5_ic", "y5_pho", "y5_sc", "y5_wr"],
			"homeroom": "y5_hr",
            "workspace": "workspace_2367"
        },
        "9012": {
            "name": "Nebil Belhaj",
			"subjects": ["y3_art", "y4_art", "y5_art", "y6A_art", "y6B_art", "y7_art", "y8_art", "y9_art"],
			"homeroom": null,
            "workspace": "workspace_9012"
        },
        "6789": {
            "name": "Nourhane Ghanem",
			"subjects": ["y3_ar", "y6A_ar", "y6B_ar", "y7_ar", "y8_ar", "y9_ar","y4_ar","y5_ar"],
			"homeroom": null,
            "workspace": "workspace_6789"
        },
        "7890": {
            "name": "Noussaier Benamor",
			"subjects": ["y3_pe", "y4_pe", "y5_pe", "y6A_pe", "y6B_pe", "y7_pe", "y8_pe", "y9_pe"],
			"homeroom": null,
            "workspace": "workspace_7890"
        },
        "4567": {
            "name": "Racha Chaabani",
			"subjects": ["y10_ph", "y11_ph", "y13_ph"],
			"homeroom": "y11_hr",
            "workspace": "workspace_4567"
        },
        "5566": {
            "name": "Salma Ben Azzouz",
			"subjects": ["y3_ma", "y4_ma", "y5_ma", "y6A_ma"],
			"homeroom": "y6A_hr",
            "workspace": "workspace_5566"
        },
        "7234": {
            "name": "Salma Djebbi",
			"subjects": ["y10_bi", "y11_bi", "y12_bi", "y13_bi"],
			"homeroom": "y10_hr",
            "workspace": "workspace_7234"
        },
        "3456": {
            "name": "Sana El-Arbi",
			"subjects": ["y4_en", "y9_en", "y4_gp", "y4_ic", "y4_pho", "y4_sc", "y4_wr"],
			"homeroom": "y4_hr",
            "workspace": "workspace_3456"
        },
        "2468": {
            "name": "Sana Mzoughi",
			"subjects": ["y6A_co", "y6B_co", "y7_co", "y8_co", "y9_co", "y10_cs", "y11_cs", "y6A_ic", "y6B_ic", "y7_ic", "y8_ic", "y9_ic"],
			"homeroom": null,
            "workspace": "workspace_2468"
        },
        "9900": {
            "name": "Sondes ben Chaaben",
            "workspace": "workspace_9900"
        },
        "5456": {
            "name": "Soufyene Ben Friha",
			"subjects": ["y11_ma", "y12_ma"],
			"homeroom": "y12_hr",
            "workspace": "workspace_5456"
        },
	  "7193": {
            "name": "Rania Ben Saad",
            "workspace": "workspace_7193"
        },
        "9228": {
            "name": "Zeyneb Fajraoui",
			"subjects": ["y6B_ma", "y7_ma", "y8_ma", "y9_ma"],
			"homeroom": "y8_hr",
            "workspace": "workspace_9228"
        },
	     "7591": {
            "name": "Youssef Torjmane",
			"subjects": ["y6B_sc", "y6A_sc","y9_sc"],
			"homeroom": "y6B_hr",
            "workspace": "workspace_7591"
        }
    },
"links": {
    "lac": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EbZ2mtH7ZVtOjtf4-Pug8gMBY_AXYOx424kwN_YhzHJoTQ?e=buIXip",
    "charguia": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EegsqjrYJz1FksYT-fel6v0BbtIu5BzM_g1hejheC4GHtw?e=svf1Hm",
    "student_lists": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EUuugrXLwG5Nmjny5kOuSooBr7gw4jcKx56fTcy47QzIzg?e=c6N2gw",
    "school_database": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ETctFyqP7YJIvJi84sjrFGcBFU7D0yLzCiPLv7mSzrY-eA?e=shN7jW",
"disciplinary_lac": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/ESZcgM1edVpImtFsxgDUF_oB-vHoQmP-UlVdX4OAXGkMLQ?e=hwxcah",
"disciplinary_charguia": "https://turkiyemaarif-my.sharepoint.com/:x:/g/personal/admin_tn_maarifschools_org/EW8KqhuwDKpMgk7VxthSdIYBC4fX8Cj4T3aqwHzykHo78A?e=NNCzcm",	
        "workspace_7591": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EsaeRsQePORBiSmXA4Z8P7ABE5fHEZ5GORXxU8XkDdwbwQ?e=fhR9o4",
	"workspace_1890": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/ElDVxEoA60xPvECyhjUBLYcBV4wZYTQGmRIjl3Mqv-Dr4g?e=1pJjVs",
        "workspace_2789": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Epl7HnvsjCRDpEzx5DR01I4B-3IV8eqWaJ5lnv8sn71Yvw?e=ApUIO8",
        "workspace_3478": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EltYjR5m10dMnvZRFMki4lABeI1a4YJogGTg6IaE85E1Cg?e=EtKpHQ",
        "workspace_8123": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EiUV7ENayqlBpdqtgPCV5BcBwrvRCyl4WcyIH8tFG060hQ?e=K03Jx9",
        "workspace_1122": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EnJ1oJ8pEAZHk1mZdp5iowQBiGp6y_hAk0lrKcMkhkLG_g?e=2ptHKN",
        "workspace_2345": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EjZRMoQ5ozZGursMO39RL1QBPScTZv2EEvSke9PgSURzGw?e=2rfwGc",
        "workspace_5678": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/ErtnuEbYy1pBiX_9cqipS_ABfwmFB6kU0NNsfvcnC6YqeQ?e=dWxbyy",
        "workspace_1243": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EjNjcVjNrq9Guhs-OIQ6w4sBdN7El7EJfibKusJbCIKA7w?e=xXhLNJ",
        "workspace_1034": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Eu2wIaWny81Cq5VC9d8sYGQBHtLy4cviNvBnRVXGL6H9pA?e=A5TdwA",
        "workspace_1357": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Ejm3WwP8rpdPpmUeQgol_6YB_-ErR2z2AeWMYqXQ2P6LoA?e=g27Ph6",
        "workspace_7618": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Esav9qfda0dKm871c2UHz08BOcQqOxQD1R8ReGyLKcxkUA?e=zfNvsI",
        "workspace_4567": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EhXGgqUrAy5FqyhlRJCUFl0BMpSpKBaon1KYDw9SlWO4Rw?e=MSqyBK",
        "workspace_6345": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EuFjk9iFOdpDr5M1h628JYoBs5VkOQ1fsZk-8om8UzXM5g?e=o8yFBB",
        "workspace_8517": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EhBCnYcSZlZMgdhHsXPxoIEB9ArHe7LERZOxUk2jm88l7A?e=TIc625",
        "workspace_7788": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EvfITWG7VuROqJd_uB8kyPYBylMayi68vXRmEQ0e514APA?e=QzMEgh",
        "workspace_4589": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EgeBacQcKyROkl3ucvV9-ngBZTukwXqCByr7dXIQ4H_Ecw?e=MC2EL1",
        "workspace_3344": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EupWgsfIcHVMplEmpA2qATMBJcuf_NJ9_2eDLjTHya0ZSA?e=yHDJ06",
        "workspace_5690": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Eir1stf9bfhDjtGXl_5YuDQBruB5cajkJFPqNWYlZhXKEQ?e=VHvSPz",
        "workspace_3678": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Eg01g590uWpAv8Blfn3SsQwBzJq_mDtAW4WI9OjuNkAkDQ?e=ZYkEHo",
        "workspace_1245": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EsMW-ti6bSNOiMY3qVzurs8BuPK5GhdSu36yjdL5v9iWBw?e=ClXhGW",
        "workspace_2367": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EvpQE5D_-lxEqNSvCgcVShwB-kZ5QM_UXF1Tnv7xSOz2gw?e=L1Bfw7",
        "workspace_9012": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EgLTJIgQOtVLj5UQCWPA1YsBzXve-1FWqkzeOuKvVOLr5A?e=1hP0Ag",
        "workspace_6789": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Etq6fIhzPfRLrWPOxzwyyw4Bo9l3mO0nz6Jr2viDkfjV0w?e=a23nuM",
        "workspace_7890": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EgSfZX_wyChFpUssQ9heADwB2K5x0iWvaCOJnBBKwMmwRA?e=dO09ar",
        "workspace_5566": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EvqaVdhU_jJFvkp7V5Rc5IQBhry2K5lwcZRbx4sVpJrY0g?e=pFrhHR",
        "workspace_7234": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EqM9PUfU7jRIlHLnfWD4llkBzAzaiu3jNiO0hMD8n8Z2XQ?e=PtDUQI",
        "workspace_3456": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EhJLf0z07uZCm6AgIBptbywBUkPNnDIZicyLSm3c_Xo2Tg?e=NwG7Cx",
        "workspace_2468": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EuE5LK6lao9MvXYy6t14E6sBAjVkHek7otFlHIjfzfDvWw?e=SiCRCG",
        "workspace_9900": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EivdztZ-7TRPhy1SN-mfe9MBGeSiM49oBxX1zPH-p39aZw?e=QjlFfl",
        "workspace_5456": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EhH1ohjwZgNJuWXvOGztrCIBVwLE9I6z-I8FOpyLKZoUKg?e=N5erMp",
	"workspace_5279": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EkfBSujm9FdGj7bUS2YR94IBYUKnNo83dck25R9N36VVOA?e=DG0OYh",
	"workspace_8493": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EsKJef33mV9In4DngG_fXkcBSJtU_8BDj2GeM8ZSdnVQUg?e=pofdsj",
	"workspace_2837": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EkfBSujm9FdGj7bUS2YR94IBYUKnNo83dck25R9N36VVOA?e=J50TOs",
        "workspace_9228": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/EsvGhYUrlXpFoK6dFyKJKxUBK-puNd4az6t6Dn9TAoFm8A?e=bDKZ4Y",
	"workspace_7193": "https://turkiyemaarif-my.sharepoint.com/:f:/g/personal/admin_tn_maarifschools_org/Ev-Fdne8WClIjsLzfQIYmxQBwGIMKmWJ55MaFTlo4Mp0PA?e=UTlauy"
   },
};
